### ISSUE TITLE
Only Yuvi with permissions in PyPI

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/gh-scoped-creds#34]
@yuvipanda I'm looking to setup jupyterhub-bot with a PyPI deployment token for this repo for #32, but I also note that we only have you as a sole maintainer of the PyPI package atm. Feel free to add me or another jupyterhub maintainer, but i figure we should be at least 2+ being able to resolve issues and avoid a bus factor of 1.

**Comment by yuvipanda** [comment]
@consideRatio I've invited you! Thank you for taking care of this <3

**Comment by consideRatio** [comment]
Thanks @yuvipanda! jupyterhub-bot added as a maintainer and a deployment token scoped for this repo setup in the github secret PYPI_PASSWORD
